print("#############################")
print("#                           #")
print("#  M Samil Rendy Nor Saleh  #")
print("#       2310817310004       #")
print("#                           #")
print("#############################")